# -*- coding: utf-8 -*-
from django.urls import path
from . import views

urlpatterns = [
    path('admin-login/', views.admin_login, name='admin-login'),
    # path('', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard_data, name='dashboard-data'),
    path('save-plan-change/', views.save_plan_change, name='save_plan_change'),
    path('pay-now/', views.pay_now, name='pay_now'),
    #path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('admin-logout/', views.admin_logout, name='admin-logout'),
    path('profile/', views.profile, name='profile'),
    path('business-info/', views.business_info, name='business-info'),
    path('developers/', views.developers, name='developers'),
    path('sub-admin/', views.sub_admin, name='sub-admin'),
    path('users/', views.users, name='users'),
    path('project-list/', views.project_list, name='project-list'),
    path('add-project-info/', views.add_project_info, name='add-project-info'),
    path('project-map-view/', views.project_map_view, name='project-map-view'),
    path('project-photo-video/', views.project_photo_video, name='project-photo-video'),
    path('project-document-floor-plan/', views.project_document, name='project-document-floor-plan'),
    path('save-facility/', views.save_facility, name='save-facility'),
    path('save-project/', views.save_project, name='save-project'),
    path('save-project-video/', views.save_project_video, name='save-project-video'),
    path('change-project-status/', views.change_project_status, name='change-project-status'),
    path('change-project-approval-status/', views.change_project_approval_status, name='change-project-approval-status'),
    path('listing/', views.listing, name='listing'),
    path('save-user-plan/', views.save_user_plan, name='save-user-plan'),
    path('check-user-exists/', views.check_user_exists, name='check-user-exists'),
    path('user-details/', views.user_details, name='user-details'),
    path('save-personal-info/', views.save_personal_info, name='save-personal-info'),
    path('website/', views.website, name='website'),
    path('change-admin-password/', views.change_admin_password, name='change-admin-password'),
    path('delete-website-user/', views.delete_website_user, name='delete-website-user'),
    path('save-images/', views.save_images, name='save-images'),
    path('delete-images/', views.delete_images, name='delete-images'),
    path('save-website-setting/', views.save_website_setting, name='save-website-setting'),
    path('add-developer/', views.add_developer, name='add-developer'),
    path('add-sub-admin/', views.add_sub_admin, name='add-sub-admin'),
    path('delete-agent/', views.delete_agent, name='delete-agent'),
    path('delete-sub-admin/', views.delete_sub_admin, name='delete-agent'),
    path('get-make-agent-details/', views.get_agent_details, name='get-make-agent-details'),
    path('upgrade-user-to-agent/', views.upgrade_user_to_agent, name='upgrade-user-to-agent'),
    path('change-user-password/', views.change_user_password, name='change-user-password'),
    path('reset-user-password/', views.reset_user_password, name='reset-user-password'),
    path('add-blog/', views.add_article, name='add-article'),
    path('blogs/', views.articles, name='articles'),
    path('edit-user-details/', views.edit_user_details, name='edit-user-details'),
    path('save-user-details/', views.save_user_details, name='save-user-details'),
    path('delete-article/', views.delete_article, name='delete-article'),
    path('bidder-registration/', views.bidder_registration, name='bidder-registration'),
    path('user-search-suggestion/', views.user_search_suggestion, name='user-search-suggestion'),
    path('agent-search-suggestion/', views.agent_search_suggestion, name='agent-search-suggestion'),
    path('sub-admin-search-suggestion/', views.sub_admin_search_suggestion, name='sub-admin-search-suggestion'),
    path('listing-property-info/', views.listing_property_info, name='listing-property-info'),
    path('listing-settings/', views.listing_settings, name='listing-settings'),
    path('get-property-info-data/', views.get_property_info_data, name='get-property-info-data'),
    path('property-map-view/', views.property_map_view, name='property-map-view'),
    path('property-photo-video/', views.property_photo_video, name='property-photo-video'),
    path('property-document/', views.property_document, name='property-document'),
    path('save-property/', views.save_property, name='save-property'),
    path('save-property-video/', views.save_property_video, name='save-property-video'),
    path('get-property-types/', views.get_property_types, name='get-property-types'),
    path('add-property-features/', views.add_property_features, name='add-property-features'),
    path('change-property-status/', views.change_property_status, name='change-property-status'),
    path('change-approval-status/', views.change_approval_status, name='change-approval-status'),
    path('user-personal-info/', views.get_user_personal_info, name='user-personal-info'),
    path('icon-by-type/', views.get_icons_by_type, name='icon-by-type'),
    path('zipcode-address-details/', views.get_address_detail_by_zipcode, name='zipcode-address-details'),
    path('contact-listing/', views.contact_listing, name='contact-listing'),
    path('contact-detail/', views.contact_detail, name='contact-detail'),
    path('listing-search-suggestion/', views.listing_search_suggestion, name='listing-search-suggestion'),
    path('contact-search-suggestion/', views.contact_search_suggestion, name='contact-search-suggestion'),
    path('blog-search-suggestion/', views.blog_search_suggestion, name='blog-search-suggestion'),
    path('delete-property/', views.delete_property, name='delete-property'),
    path('delete-project/', views.delete_project, name='delete-project'),
    path('save-listing-settings/', views.save_listing_settings, name='save-listing-settings'),
    path('get-listing-settings/', views.get_listing_settings, name='get-listing-settings'),
    path('article-search-suggestion/', views.article_search_suggestion, name='article-search-suggestion'),
    path('chat/', views.chat_list, name='chat'),
    # path('chat-history/', views.chat_history, name='chat-history'),
    path('save-chat-message/', views.save_chat_message, name='save-chat-message'),
    path('preview-theme/', views.preview_theme, name='preview-theme'),
    path('get-chat-count/', views.get_chat_count, name='get-chat-count'),
    path('bidder-registration-details/', views.bidder_registration_details, name='bidder-registration-details'),
    path('save-bidder-document/', views.save_bidder_document, name='save-bidder-document'),
    path('delete-bidder-document/', views.delete_bidder_documents, name='delete-bidder-document'),
    path('delete-bidder-reg/', views.delete_bidder_reg, name='delete-bidder-reg'),
    path('bidder-reg-search-suggestion/', views.bidder_registration_search_suggestion, name='bidder-reg-search-suggestion'),
    path('property-bidder-registration/', views.property_bidder_registration, name='property-bidder-registration'),
    path('property-bid-history/', views.property_bid_history, name='property-bid-history'),
    path('popup-bidder-reg-search-suggestion/', views.popup_bidder_registration_search_suggestion, name='popup-bidder-reg-search-suggestion'),
    path('user-bid-reg-list/', views.user_bid_reg_list, name='user-bid-reg-list'),
    # path('schedule-tour-list/', views.schedule_tour_list, name='schedule-tour-list'),
    path('property-listing-ordering/', views.property_listing_ordering, name='property-listing-ordering'),
    path('schedule-search-suggestion/', views.schedule_search_suggestion, name='schedule-search-suggestion'),
    path('get-plan-history/', views.get_plan_history, name='get-plan-history'),
    path('about-us/', views.about_us, name='about-us'),
    path('save-cms/', views.save_cms, name='save-cms'),
    path('contact-us/', views.contact_us, name='contact-us'),
    path('terms/', views.terms, name='terms'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('email-template/', views.email_template, name='email-template'),
    path('add-template/', views.add_template, name='add-template'),
    path('template-search-suggestion/', views.template_search_suggestion, name='template-search-suggestion'),
    # auction dashboard
    path('auction-dashboard/', views.auction_dashboard, name='admin-auction-dashboard'),
    path('auction-search-suggestion/', views.auction_search_suggestion, name='auction-search-suggestion'),
    path('update-reserve-price/', views.update_reserve_price, name="admin-auction-reserve-update"),
    path('update-bid-increment/', views.update_bid_increment, name="admin-auction-bid-increment"),
    path('start-stop-bid-auction/', views.start_stop_bid_auction, name="admin-stop-bid-auction"),
    path('edit-auction/', views.edit_auction, name="admin-edit-auction"),
    path('email-all-users/', views.email_auction_users, name="admin-auction-email"),
    path('fetch-auction-bids/', views.auction_bid_history, name="auction-bid-history"),
    path('fetch-auction-bidders/', views.auction_bidder_history, name="auction-bidder-history"),
    path('fetch-auction-watchers/', views.auction_watcher_history, name="auction-watcher-history"),
    path('new-bid-checked/', views.new_bid_checked, name="admin-newbid-checked"),
    path('get-auction-type-status/', views.get_auction_type_status, name="get-auction-type-status"),
    path('property-offer-list/', views.property_offer_list, name="property-offer-list"),
    path('property-offer-details/', views.property_offer_details, name="property-offer-details"),
    path('counter-offer-details/', views.counter_offer_details, name="counter-offer-details"),
    path('accept-offer/', views.seller_accept_offer, name="accept-offer"),
    path('reject-offer/', views.seller_reject_offer, name="reject-offer"),
    path('counter-offer/', views.seller_counter_offer, name="counter-offer"),
    path('get-offer-doc-details/', views.get_offer_document_details, name="get-offer-doc-details"),
    path('chat-to-buyer/', views.chat_to_buyer, name="chat-to-buyer"),
    path('download-listing/', views.download_listing, name="download-listing"),
    path('property-best-offer-list/', views.property_best_offer_list, name="property-best-offer-list"),
    path('property-best-offer-details/', views.property_best_offer_details, name="property-best-offer-details"),
    path('export-bid-history/', views.export_bid_history, name="export-bid-history"),
    path('delete-current-bid/', views.delete_current_bid, name="delete-current-bid"),
    path('download-loi/', views.download_loi, name="download-loi"),
    path('send-loi/', views.seller_send_loi, name="send-loi"),
    path('download-invoice/', views.download_payment_invoice, name="download-invoice"),
    path('user-best-offer-list/', views.user_best_offer_list, name="user-best-offer-list"),
    path('approve-best-offer/', views.seller_approve_best_offer, name="approve-best-offer"),
    path('accept-best-offer/', views.seller_accept_best_offer, name="accept-best-offer"),
    path('reject-best-offer/', views.seller_reject_best_offer, name="reject-best-offer"),
    path('counter-best-offer/', views.seller_counter_best_offer, name="counter-best-offer"),
    path('user-traditional-offer-list/', views.user_traditional_offer_list, name="user-traditional-offer-list"),
    path('change-theme/', views.change_theme, name="change-theme"),
    path('counter-best-offer-details/', views.counter_best_offer_details, name="counter-best-offer-details"),
    path('best-offer-history-details/', views.best_offer_history_details, name="best-offer-history-details"),
    path('check-user-pass/', views.check_user_pass, name="check-user-pass"),
    path('export-bidder-list/', views.export_bidder_list, name="export-bidder-list"),
    path('export-auction-bidders/', views.export_auction_bidders, name="export-auction-bidders"),
    path('export-auction-bids/', views.export_auction_bids, name="export-auction-bids"),
    path('export-watchers/', views.export_watchers, name="export-watchers"),
    path('insider-property-bid-history/', views.insider_property_bid_history, name='insider-property-bid-history'),
    path('export-insider-bid-history/', views.export_insider_bid_history, name="export-insider-bid-history"),
    # path('property-estimator-list/', views.subdomain_property_estimator_list, name="property-estimator-list"),
    path('insider-auction-dashboard/', views.insider_auction_dashboard, name='insider-auction-monitor'),
    path('estimator-assign-agent/', views.estimator_assign_agent, name="estimator-assign-agent"),
    # path('property-estimator-details/', views.domain_property_estimator_details, name="property-estimator-details"),
    path('estimator-change-status/', views.estimator_change_status, name="estimator-change-status"),
    path('estimator-send-message/', views.estimator_send_message, name="estimator-send-message"),
    path('portfolio-list/', views.portfolio_list, name="portfolio-list"),
    path('add-portfolio/', views.add_portfolio, name="add-portfolio"),
    path('send-reset-password-link/', views.send_reset_password_link, name='send_reset_password_link'),
    path('property-total-view/', views.property_total_view, name='property-total-view'),
    path('export-property-total-view/', views.export_property_total_view, name="export-property-total-view"),
    path('email-all-property-viewer/', views.email_all_property_viewer, name="email-all-property-viewer"),
    path('property-total-watcher/', views.property_total_watcher, name='property-total-watcher'),
    path('export-property-total-watcher/', views.export_property_total_watcher, name="export-property-total-watcher"),
    path('user-property-bid-history/', views.user_property_bid_history, name='user-property-bid-history'),
    path('property-total-bid/', views.property_total_bid, name='property-total-bid'),
    path('send-message-to-agent/', views.send_message_to_agent, name='property-total-bid'),
    path('update-subscription-plan/', views.update_subscription_plan, name='update-subscription-plan'),
    path('check-payment/', views.check_payment, name='check_payment'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('add-testimonial/', views.add_testimonials, name='add_testimonials'),
    path('testimonials-search-suggestion/', views.testimonials_search_suggestion, name='testimonial-search-suggestion'),
    path('state-list/', views.state_list, name='state-list'),
    path('update-dashboard/', views.update_dashboard, name='update-dashboard'),
    path('update-signup-view-graph/', views.update_signup_view_graph, name='update-signup-view-graph'),
    path('update-property-registration-graph/', views.update_property_registration_graph, name='update-property-registration-graph'),
    path('update-dashboard-map/', views.update_dashboard_map, name='update-dashboard-map'),
    path('close-tour/', views.close_tour, name='close-tour'),
    path('send-email-verification-link/', views.send_email_verification_link, name='send_email_verification_link'),
    path('upload-csv/', views.upload_csv, name='upload_csv'),
    path('payment-settings/', views.payment_settings, name='payment-settings'),
    path('save-payment-settings/', views.save_payment_settings, name='save-payment-settings'),
    
    # CMS management
    path('cms-list/', views.cms_list, name="admin-cms-list"),
    path('ajax-cms-list/', views.ajax_cms_list, name="ajax-admin-cms-list"),
    path('active-inactive-cms/', views.active_inactive_cms, name="admin-cms-status-change"), 
    path('add-cms/', views.add_cms, name="admin-add-cms"),
    path('ajax-add-cms/', views.ajax_add_cms, name="admin-ajax-add-cms"),
    path('edit-cms/<int:id>', views.edit_cms, name="admin-edit-cms") ,

    # FAQ management
    path('faq-list/', views.faq_list, name="admin-faq-list"),
    path('ajax-faq-list/', views.ajax_faq_list, name="ajax-admin-faq-list"),
    path('add-faq/', views.add_faq, name="admin-add-faq"),
    path('ajax-add-faq/', views.ajax_add_faq, name="admin-ajax-add-faq"),
    path('edit-faq/<int:id>', views.edit_faq, name="admin-edit-faq"),

    # Blog management
    # path('blog-list/', views.blog_list, name="admin-blog-list"),
    # path('ajax-blog-list/', views.ajax_blog_list, name="ajax-admin-blog-list"),
    # path('active-inactive-blog/', views.active_inactive_blog, name="admin-blog-status-change"), 
    # path('add-blog/', views.add_blog, name="admin-add-blog"),
    # path('ajax-add-blog/', views.ajax_add_blog, name="admin-ajax-add-blog"),
    # path('edit-blog/<int:id>', views.edit_blog, name="admin-edit-blog") ,


    # Video Tutorials
    # path('video-list/', views.video_list, name="admin-video-list"),
    path('ajax-video-list/', views.ajax_video_list, name="ajax-admin-video-list"),
    # path('active-inactive-video/', views.active_inactive_video, name="admin-video-status-change"), 
    path('ajax-add-video/', views.ajax_add_video, name="admin-ajax-add-video"),
    path('ajax-get-video-details/', views.ajax_video_details, name="admin-ajax-video-details"),

    # Email Template Management
    path('email-template-list/', views.email_template_list, name="admin-email-template"),
    path('ajax-email-template-list/', views.ajax_email_template_list, name="ajax-admin-email-template-list"),
    path('active-inactive-email-template/', views.active_inactive_email_template, name="admin-email-template-status-change"), 
    path('add-email-template/', views.add_email_template, name="admin-add-email-template"),
    path('ajax-add-email-template/', views.ajax_add_email_template, name="admin-ajax-add-email-template"),
    path('edit-email-template/<int:id>', views.edit_email_template, name="admin-edit-email-template") ,

    # Estimator category
    path('estimator-category-list/', views.estimator_category_list, name="estimator-category-list"),
    path('get-estimator-category-details/', views.get_estimator_category_details, name="get-estimator-category-details"),
    path('save-estimator-category/', views.save_estimator_category, name="save-estimator-category"),
    # Estimator category
    path('estimator-question-list/', views.estimator_question_list, name="estimator-question-list"),
    path('save-estimator-question/', views.save_estimator_question, name="save-estimator-question"),
    path('estimator-list/', views.property_estimator_list, name="property-estimator-list"),
    path('estimator-details/', views.property_estimator_details, name="property-estimator-details"),
    path('get-latitude-longitude/', views.get_latitude_longitude, name='get-latitude-longitude'),

    # Advertisement
    path('advertisement-list/', views.advertisement_list, name="admin-advertisement-list"),
    path('ajax-advertisement-list/', views.ajax_advertisement_list, name="ajax-admin-advertisement-list"),
    path('save-advertisement/', views.save_advertisement, name='admin-save-advertisement'),
    path('ajax-get-advertisement-details/', views.ajax_advertisement_details, name="admin-ajax-advertisement-details"),

    path('admin-save-images/', views.admin_save_images, name='admin-save-images'),

    path('verify-email/', views.verify_email, name='verify-email'),
    path('update-dashboard-data/', views.update_dashboard_data, name='update-dashboard-data'),
    
    #Employee
    path('employee/', views.employee, name='employee'),
    path('add-employee/', views.add_employee, name='add-employee'),
    path('employee-search-suggestion/', views.employee_search_suggestion, name='employee-search-suggestion'),
    path('delete-employee/', views.delete_employee, name='delete-employee'),
    path('user-verification/', views.user_verification, name='user-verification'),
    path('employee-csv-download/', views.employee_csv_download, name='employee-csv-download'),

    #addlisting
    path('add-listing/', views.add_listing, name='add-listing'),
    path('get-municipality/', views.get_municipality, name='get-municipality'),
    path('get-district/', views.get_district, name='get-district'),
    path('get-community/', views.get_community, name='get-community'),
    path('save-listing/', views.save_listing, name='save-listing'),
    path('auction-detail/', views.auction_detail, name='auction-detail'),
    
    path('property-total-favourite/', views.property_total_favourite, name='property-total-favourite'),
    path('export-property-total-favourite/', views.export_property_total_favourite, name="export-property-total-favourite"),
    path('property-total-interest/', views.property_total_interest, name='property-total-interest'),
    path('export-property-total-interest/', views.export_property_total_interest, name="export-property-total-interest"),
    path('developer-csv-download/', views.developer_csv_download, name='developer-csv-download'),
    path('sub-admin-csv-download/', views.sub_admin_csv_download, name='sub-admin-csv-download'),
    path('users-csv-download/', views.users_csv_download, name='users-csv-download'),
    path('projects-csv-download/', views.projects_csv_download, name='projects-csv-download'),
    
    path('property-buy-now/', views.property_buy_now, name='property-buy-now'),
    path('export-property-buy-now/', views.export_property_buy_now, name="export-property-buy-now"),
    path('accept-buy-now/', views.accept_buy_now, name='accept-buy-now'),

    path('change-password/', views.change_password, name='change-password'),
    path('user-profile/', views.user_profile, name='user-profile'),
    path('make-highest-bid/', views.make_highest_bid, name='make-highest-bid'),
    path('highest-bidder-details/', views.highest_bidder_details, name='highest-bidder-details'),
    path('download-listing-csv/', views.download_listing_csv, name='download_listing_csv'),
    path('property-relist/', views.property_relist, name='property-relist'),
    path('get-construction-status/', views.get_construction_status, name='get-construction-status'),

]
