residential_loan_types = [
    {'id':1, 'name': 'No Loan'},
    {'id':2, 'name': 'Conventional Loan'},
    {'id':4, 'name': 'VA Loan'},
    {'id':3, 'name': 'FHA Loan'},
    {'id':8, 'name': 'USDA/FSA Loan'},
    {'id':6, 'name': '1031 Exchange'},
    {'id':9, 'name': 'Bridge Loan'},
    {'id':10, 'name': 'Jumbo Loan'},
    {'id':7, 'name': 'Other'}
]

commerical_loan_types = [
    {'id':1, 'name': 'No Loan'},
    {'id':2, 'name': 'Conventional Loan'},
    {'id':8, 'name': 'USDA/FSA Loan'},
    {'id':5, 'name': 'SBA Loan'},
    {'id':6, 'name': '1031 Exchange'},
    {'id':11, 'name': 'Conduit/CMBS Loan'},
    {'id':9, 'name': 'Bridge Loan'},
    {'id':10, 'name': 'Jumbo Loan'},
    {'id':7, 'name': 'Other'}
]

land_loan_types  = [
    {'id':1, 'name': 'No Loan'},
    {'id':2, 'name': 'Conventional Loan'},
    {'id':8, 'name': 'USDA/FSA Loan'},
    {'id':6, 'name': '1031 Exchange'},
    {'id':9, 'name': 'Bridge Loan'},
    {'id':7, 'name': 'Other'}
]

PROPERTY_FEATURE_LOOKUPS = {
    'property_type': 'Property Type',
    'property_subtype': 'Property Sub Type',
    "terms_accepted": 'Terms Accepted',
    "occupied_by": 'Occupied By',
    "ownership": 'Ownership',
    "possession": 'Possession',
    "lot_size": 'Lot Unit',
    "style": 'Style',
    "cooling": 'Cooling',
    "stories": 'Stories',
    "heating": 'Heating',
    "electric": 'Electric',
    "gas": 'Gas',
    "recent_updates": 'Recent Updates',
    "water": 'Water',
    "security_features": 'Security Features',
    "sewer": 'Sewer',
    "tax_exemptions": 'Tax Exemptions',
    "zoning": 'Zoning',
    "amenities": 'Hoa Amenities',
    "kitchen_features": 'Kitchen Features',
    "appliances": 'Appliances',
    "flooring": 'Flooring',
    "windows": 'Windows',
    "bedroom_features": 'Bedroom Features',
    "bathroom_features": 'Bathroom Features',
    "other_rooms": 'Other Rooms',
    "other_features": 'Other Features',
    "master_bedroom_features": 'Master Bedroom Features',
    "fireplace_type": 'Fire place',
    "basement_features": 'Basement Features',
    "handicap_amenities": 'Handicap Amenities',
    "construction": 'Construction',
    "exterior_features": 'Exterior Features',
    "garage_parking": 'Garage Parking',
    "garage_features": 'Garage Features',
    "roof": 'Roof',
    "outbuildings": 'Outbuildings',
    "foundation": 'Foundation',
    "location_features": 'Location Features',
    "fence": 'Fence',
    "road_frontage": 'Road Frontage',
    "pool": 'Pool',
    "property_faces": 'Property Faces',
    "lease_type": 'LeaseType',
    "tenant_pays": 'Tenant Pays',
    "inclusions": 'Inclusions',
    "building_class": 'Building Class',
    "interior_features": 'Interior Features',
    "mineral_rights": 'Mineral Rights',
    "easements": 'Easements',
    "survey": 'Survey',
    "utilities": 'Utilities',
    "improvements": 'Improvements',
    "topography": 'Topography',
    "wildlife": 'Wildlife',
    "fish": 'Fish',
    "irrigation_system": 'Irrigation System',
    "recreation": 'Recreation',
}

url_for_permission = {
    "sub-admin": 1,
    "add-sub-admin": 1,
    "users": 4,
    "developers": 26,
    "add-developer": 26,
    "employee": 27,
    "add-employee": 27,
    "business-info": 7,
    "project-list": 24,
    "add-project-info": 24,
    "listing": 6,
    "add-listing": 6,
    "listing-settings": 6,
    "auction-dashboard": 25,
    "bidder-registration": 2,
    "settings": 17,
    "cms-list": 16,
    "blogs": 16,
    "faq-list": 16,
    "email-template-list": 16,
    "add-email-template": 16,
    "add-cms": 16,
    "add-blog": 16,
    "add-faq": 16,
    "advertisement-list": 22,
    "chat": 18,
    "contact-listing": 12
}